project:
  title: "Otho Mantegazza"
  type: website
  output-dir: docs
  render:
    - "*.qmd"
  preview:
    port: 4200

format:
  html:
    theme: default
    css: style/custom.scss
    fontsize: 24px
    toc: true

website:
  page-footer:
    left:
      - text: "License"
        href: license.qmd
  sidebar:
    style: "docked"
    background: "white"
    foreground: "black"
    search: false
    contents:
      - section: "Portfolio"
        contents: 
          - text: "Projects"
            file: projects.qmd
          - text: "Trainings"
            file: trainings.qmd
      - text: "CV"
        file: cv.qmd
      - text: "Else"
        file: else.qmd
      - text: "Values / Ethics"
        file: values.qmd
      - text: "Contact"
        file: contact.qmd


execute:
  freeze: auto

