project:
  title: "Otho Mantegazza"
  type: website
  output-dir: docs
  render:
    - "*.qmd"
  resources:
    - img/
  preview:
    port: 4200

format:
  html:
    theme: default
    css: style/custom.css
    fontsize: 24px
    toc: true

website:
  page-footer:
    left:
      - text: "License"
        href: license.qmd
    right:
      - icon: github
        href: https://github.com/othomantegazza
      - icon: linkedin
        href: https://www.linkedin.com/in/otho-mantegazza/
      - icon: twitter
        href: https://twitter.com/othomn
  sidebar:
    style: "docked"
    background: "white"
    foreground: "black"
    search: false
    contents:
      - section: "Portfolio"
        contents: 
          - text: "Projects"
            file: projects.qmd
          - text: "Trainings"
            file: trainings.qmd
      - text: "CV"
        file: cv.qmd
      - text: "Else"
        file: else.qmd
      - text: "Hire me"
        file: hire-me.qmd
      # - text: "Values / Ethics"
      #   file: values.qmd
      - text: "Contact"
        file: contact.qmd


execute:
  freeze: auto

