project:
  title: "Otho Mantegazza"
  type: website
  output-dir: docs
  render:
    - index.qmd
    - content/*.qmd
  preview:
    port: 4200

format:
  html:
    theme: default
    css: style/custom.scss
    fontsize: 24px
    toc: true

website:
  page-footer:
    left:
      - text: "License"
        href: content/license.qmd
  sidebar:
    style: "docked"
    background: "white"
    foreground: "black"
    search: false
    contents:
      - section: "Portfolio"
        contents: 
          - text: "Projects"
            file: content/projects.qmd
          - text: "Trainings"
            file: content/trainings.qmd
      - text: "CV"
        file: content/cv.qmd
      - text: "Else"
        file: content/else.qmd
      - text: "Values / Ethics"
        file: content/values.qmd
      - text: "Contact"
        file: content/contact.qmd


      
      

execute:
  freeze: auto

