project:
  title: "Otho's Website"
  type: website
  output-dir: docs
  render:
    - index.qmd
  preview:
    port: 4200


format:
  html:
    theme: default
    css: style/custom.scss
    #page-layout: custom

execute:
  freeze: auto

