---
title: "Projects"
editor_options: 
  chunk_output_type: console
---

```{r}
#| echo: false
source(
  here::here('R/make-content-component.R') 
)
```

<hr>

## Quantum Open Source Developer Survey

```{r}
#| echo: false  
#| results: asis 
make_project_comp(
  proj_yaml = here::here('data/uf-report.yaml'),
  vid_cover = T
) 
```

<hr>

## The Tragedy of Visas

```{r}
#| echo: false  
#| results: asis 
make_project_comp(
  proj_yaml = here::here('data/tragedy-of-visas.yaml'),
  vid_cover = T
) 
```

<hr>

## Milan Air Quality V2
  
```{r}
#| echo: false  
#| results: asis 
make_project_comp(
  proj_yaml = here::here('data/milan-airquality-v2.yaml'),
  vid_cover = T
)
```

<hr>

## Milan Air Quality Dashboard

```{r}
#| echo: false  
#| results: asis 
make_project_comp(
  proj_yaml = here::here('data/milan-airquality.yaml'),
  vid_cover = T
)
```

<hr>

## Fluidigr

```{r}
#| echo: false  
#| results: asis 
make_project_comp(
  proj_yaml = here::here('data/fluidigr.yaml'),
  vid_cover = F
)
```

<hr>

## Ptrapr

```{r}
#| echo: false  
#| results: asis 
make_project_comp(
  proj_yaml = here::here('data/ptrapr.yaml'),
  vid_cover = F
) 
```

<hr>

## Sunday Blues Blog

```{r}
#| echo: false  
#| results: asis 
make_project_comp(
  proj_yaml = here::here('data/sunday-blues.yaml'),
  vid_cover = T
) 
```

<hr>

## Photosynthesis Booklet

```{r}
#| echo: false  
#| results: asis 
make_project_comp(
  proj_yaml = here::here('data/what-the-plant.yaml'),
  vid_cover = F
) 
```

<hr>

## Crossr

```{r}
#| echo: false  
#| results: asis 
make_project_comp(
  proj_yaml = here::here('data/crossr.yaml'),
  vid_cover = T
) 
```
