---
title: "Trainings"
editor_options: 
  chunk_output_type: console
---

```{r}
#| echo: false
source(
  here::here('R/make-content-component.R') 
)
```

<hr>

### CBSER - Summer School

```{r}
#| echo: false  
#| results: asis 
make_project_comp(
  proj_yaml = here::here('data/cbser.yaml'),
  vid_cover = T
)
```

<hr>

### Intro to EDA in R - Workshop

```{r}
#| echo: false  
#| results: asis 
make_project_comp(
  proj_yaml = here::here('data/eda-class.yaml'),
  vid_cover = T
)
```

<hr>

### Statistical Burger - Lunch

```{r}
#| echo: false  
#| results: asis 
make_project_comp(
  proj_yaml = here::here('data/stat-burger.yaml'),
  vid_cover = T
)
```

### Make Science with Data - Workshop

```{r}
#| echo: false  
#| results: asis 
make_project_comp(
  proj_yaml = here::here('data/sci-data-qb.yaml'),
  vid_cover = F
)
```

### Diventa Data Scientist - Online Class

```{r}
#| echo: false  
#| results: asis 
make_project_comp(
  proj_yaml = here::here('data/fed-data-sci.yaml'),
  vid_cover = F
)
```
