---
title: "Values"
---

When I started working independently, I wanted to define a set of values to guide me through the jobs and the projects that could be lying ahead of me.

At that moment I had many unorganized ideas about what those values could be, since I never had been in a position where I had to formalize them. So I was left with the ungrateful work of sorting through those ideas, hoping something sensible would emerge.

After many conversations with friends and after many evenings spent surveying my thoughts, evaluating them, organizing them, and, eventually, writing them down, over and over again, I could finally distill a set of values. They are divided in three principles which I try to follow with my work; here they are.


## Teach

Or, better, share the knowledge that you've worked so hard to gain; because the bulk of it was, in turn, shared with you by others. After knowledge was given to you, you might have been lucky enough to enrich it and let it grow, adding a small part of yourself to it; coming from your thoughts, your ideas or your research. 

Don’t get attached to what knowledge you share, and above all don’t expect others to pick it up. Trust them, instead, to be able to discern which bits of it are important and useful for them, and which aren’t. If you are lucky, you can use their feedback to improve your teaching material, your style and your approach.

Sharing knowledge empowers others and helps you. Only by communicating what you know to others, you could see it with critical enough eyes, setting you on the path to realize what's great about it, what's missing and what's wrong.

## Critically Create

Creativity is the yin to your critical-thinking yang. Creativity and critical thinking are two forces that oppose one another but depend on each other. Without creativity, there would be nothing to critique; without critical thinking, everything would be unexpected and innovative, and thus none of it would be.

Nurture and protect them both. Balance them.

Use them, in turn, to improve your work. Get lost in creativity and chisel your creation through hard critique, break down your securities with hard critique, and when nothing stands, build your way out through creativity.

Only when you balance creativity and critique, effective solutions arise.

## Make Your Work Worth It

Work is not just action in exchange for money or other commodities. 

Work is impact. Through our work we impact the communities that surround us and the ecosystem in which we act.

It’s true that through work we generate our income. But, if by generating income for ourselves we subtract equal or more value to the ecosystem that surrounds us, work becomes by definition unsustainable.

Check that the outcome of your work is sustainable and that society benefits from it as much as you do.
